=== jovansx/vaccination-system/official-system/src/main/resources/static/xsd/izvestaj_o_imunizaciji.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.akatsuki.org/izvestaj_o_imunizaciji"
    xmlns="http://www.akatsuki.org/izvestaj_o_imunizaciji"
    xmlns:o="http://www.akatsuki.org/izvestaj_o_imunizaciji"
    xmlns:t="http://www.akatsuki.org/tipovi">
    <xs:import namespace="http://www.akatsuki.org/tipovi" schemaLocation="tipovi.xsd"/>
    <xs:element name="izvestaj_o_imunizaciji">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="period">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="od" type="xs:date"/>
                            <xs:element name="do" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dokumenti">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="interesovanje_za_imunizaciju">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="zeleni_sertifikat">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="primljeno">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:int">
                                                  <xs:minInclusive value="0"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="izdato">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:int">
                                                  <xs:minInclusive value="0"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="doze_vakcina">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="raspodela_po_dozama">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" minOccurs="0" name="doza">
                                            <xs:complexType>
                                                <xs:attribute name="broj">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:int">
                                                  <xs:minInclusive value="1"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                </xs:attribute>
                                                <xs:attribute name="kolicina">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:int">
                                                  <xs:minInclusive value="1"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                                <xs:unique name="BrojDozeUnique">
                                    <xs:selector xpath="o:doza"/>
                                    <xs:field xpath="@broj"/>
                                </xs:unique>
                            </xs:element>
                            <xs:element name="raspodela_po_proizvodjacima">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="5" minOccurs="5" name="proizvodjac">
                                            <xs:complexType>
                                                <xs:attribute name="naziv" type="t:TNazivVakcine"/>
                                                <xs:attribute name="kolicina">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:int">
                                                  <xs:minInclusive value="0"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                                <xs:unique name="NazivProizvodjacaUnique">
                                    <xs:selector xpath="o:proizvodjac"/>
                                    <xs:field xpath="@naziv"/>
                                </xs:unique>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="izdato">
                            <xs:simpleType>
                                <xs:restriction base="xs:int">
                                    <xs:minInclusive value="1"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="datum_izdavanja" type="xs:date"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== jovansx/vaccination-system/dokumenti/izvestaj_o_imunizaciji.xml
<?xml version="1.0" encoding="UTF-8"?>
<izvestaj_o_imunizaciji  
    xmlns="http://www.akatsuki.org/izvestaj_o_imunizaciji"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:t="http://www.akatsuki.org/tipovi"
    xsi:schemaLocation="http://www.akatsuki.org izvestaj_o_imunizaciji.xsd
    http://www.akatsuki.org/tipovi tipovi.xsd" datum_izdavanja="2021-09-11">
    <period>
        <od>2021-08-01</od>
        <do>2021-09-01</do>
    </period>
    <dokumenti>
        <interesovanje_za_imunizaciju property="pred:broj_interesovanja" datatype="xs:int">2758</interesovanje_za_imunizaciju>
        <zeleni_sertifikat>
            <primljeno property="pred:primljeno_zelenih" datatype="xs:int">453</primljeno>
            <izdato property="pred:izdato_zelenih" datatype="xs:int">428</izdato>
        </zeleni_sertifikat>
    </dokumenti>
    <doze_vakcina izdato="3225">
        <raspodela_po_dozama>
            <doza broj="1" kolicina="1789"/>
            <doza broj="2" kolicina="1276"/>
            <doza broj="3" kolicina="160"/>
        </raspodela_po_dozama>
        <raspodela_po_proizvodjacima>
            <proizvodjac naziv="Pfizer-BioNTech" kolicina="1625"/>
            <proizvodjac naziv="Sinopharm" kolicina="1100"/>
            <proizvodjac naziv="Sputnik V (Gamaleya istrazivacki centar)" kolicina="356"/>
            <proizvodjac naziv="AstraZeneca" kolicina="144"/> 
            <proizvodjac naziv="Moderna" kolicina="5"/>   
        </raspodela_po_proizvodjacima>
    </doze_vakcina>
</izvestaj_o_imunizaciji>
