=== jovansx/vaccination-system/immunization-system/src/main/resources/static/xsd/digitalni_sertifikat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:t="http://www.akatsuki.org/tipovi"
           xmlns:o="http://www.akatsuki.org/digitalni_sertifikat"
           elementFormDefault="qualified" targetNamespace="http://www.akatsuki.org/digitalni_sertifikat"
           xmlns="http://www.akatsuki.org/digitalni_sertifikat">
    <xs:import namespace="http://www.akatsuki.org/tipovi" schemaLocation="tipovi.xsd"/>
    <xs:element name="digitalni_sertifikat">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="primalac" type="t:TPodnosilacZahteva"/>

                <xs:element name="vakcinacija">
                    <xs:complexType>
                        <xs:sequence minOccurs="2" maxOccurs="unbounded">
                            <xs:element name="doza">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tip" type="t:TTipVakcine"/>
                                        <xs:element name="proizvodjac_i_serija" type="xs:string"/>
                                        <xs:element name="datum" type="xs:date"/>
                                        <xs:element name="zdravstvena_ustanova" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="broj" type="xs:int"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    <xs:unique name="BrojDoze">
                        <xs:selector xpath="o:doza"/>
                        <xs:field xpath="@broj"/>
                    </xs:unique>
                </xs:element>

                <xs:element name="testovi">
                    <xs:complexType>
                        <xs:sequence minOccurs="3" maxOccurs="3">
                            <xs:element name="test">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="vrsta_uzorka" type="xs:string"/>
                                        <xs:element name="proizvodjac" type="xs:string"/>
                                        <xs:element name="datum_uzorkovanja" type="xs:dateTime"/>
                                        <xs:element name="datum_izdavanja_rezultata"
                                                    type="xs:dateTime"/>
                                        <xs:element name="rezultat" type="xs:string"/>
                                        <xs:element name="laboratorija" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="qr_code" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="datum_i_vreme_izdavanja" use="required" type="xs:dateTime"/>
            <xs:attribute name="broj_sertifikata" use="required" type="xs:string"/>
            <xs:attribute name="about" type="xs:string" use="required"/>
            <xs:attribute fixed="pred:parentTo" name="rel" type="xs:string"/>
            <xs:attribute name="href" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== jovansx/vaccination-system/dokumenti/digitalni_sertifikat.xml
<?xml version="1.0" encoding="UTF-8"?>
<digitalni_sertifikat 
    xmlns="http://www.akatsuki.org/digitalni_sertifikat"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:t="http://www.akatsuki.org/tipovi"
    xsi:schemaLocation="http://www.akatsuki.org digitalni_sertifikat.xsd
    http://www.akatsuki.org/tipovi tipovi.xsd"
    datum_i_vreme_izdavanja="2001-10-26T21:32:52" broj_sertifikata="2352">
    <primalac>
        <t:ime>Aleksandar</t:ime>
        <t:prezime>Buljevic</t:prezime>
        <t:jmbg>1510999800078</t:jmbg>
        <t:pol>Muski</t:pol>
        <t:broj_pasosa>792875436</t:broj_pasosa>
        <t:datum_rodjenja>1999-10-15</t:datum_rodjenja>
    </primalac>
    <vakcinacija>
        <doza broj="1">
            <tip nazivVakcine="Pfizer-BioNTech"></tip>
            <proizvodjac_i_serija>BIONTECH MANUFACTURING GMBH</proizvodjac_i_serija>
            <datum>2021-09-09</datum>
            <zdravstvena_ustanova>Promenada u Novom Sadu</zdravstvena_ustanova>
        </doza>
        <doza broj="2">
            <tip nazivVakcine="Pfizer-BioNTech"></tip>
            <proizvodjac_i_serija>BIONTECH MANUFACTURING GMBH</proizvodjac_i_serija>
            <datum>2021-09-09</datum>
            <zdravstvena_ustanova>Promenada u Novom Sadu</zdravstvena_ustanova>
        </doza>
    </vakcinacija>
    <testovi>
        <test>
            <vrsta_uzorka>N/A</vrsta_uzorka>
            <proizvodjac>f</proizvodjac>
            <datum_uzorkovanja>2001-10-26T21:32:52</datum_uzorkovanja>
            <datum_izdavanja_rezultata>2001-10-26T21:32:52</datum_izdavanja_rezultata>
            <rezultat>N/A</rezultat>
            <laboratorija>N/A</laboratorija>
        </test>
        <test>
            <vrsta_uzorka>N/A</vrsta_uzorka>
            <proizvodjac>N/A</proizvodjac>
            <datum_uzorkovanja>2001-10-26T21:32:52</datum_uzorkovanja>
            <datum_izdavanja_rezultata>2001-10-26T21:32:52</datum_izdavanja_rezultata>
            <rezultat>N/A</rezultat>
            <laboratorija>N/A</laboratorija>
        </test>
        <test>
            <vrsta_uzorka>N/A</vrsta_uzorka>
            <proizvodjac>N/A</proizvodjac>
            <datum_uzorkovanja>2001-10-26T21:32:52</datum_uzorkovanja>
            <datum_izdavanja_rezultata>2001-10-26T21:32:52</datum_izdavanja_rezultata>
            <rezultat>N/A</rezultat>
            <laboratorija>N/A</laboratorija>
        </test>
    </testovi>
</digitalni_sertifikat>
