=== jovansx/vaccination-system/immunization-system/src/main/resources/static/xsd/saglasnost_za_imunizaciju.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.akatsuki.org/saglasnost_za_imunizaciju"
    xmlns="http://www.akatsuki.org/saglasnost_za_imunizaciju"
    xmlns:o="http://www.akatsuki.org/saglasnost_za_imunizaciju"
    xmlns:t="http://www.akatsuki.org/tipovi">
    <xs:import namespace="http://www.akatsuki.org/tipovi" schemaLocation="tipovi.xsd"/>
    <xs:element name="saglasnost_za_imunizaciju">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pacijent">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="drzavljanstvo">
                                <xs:complexType>
                                    <xs:choice>
                                        <xs:element name="srpsko">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="id_broj" type="t:TCIdBroj"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="strano">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="naziv" type="xs:string"/>
                                                  <xs:element name="id_broj" type="t:TCIdBroj"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="prezime" type="t:TPrezime"/>
                            <xs:element name="ime" type="t:TIme"/>
                            <xs:element name="ime_roditelja" type="xs:string"/>
                            <xs:element name="pol" type="t:TCPol"/>
                            <xs:element name="rodjenje">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="datum_rodjenja" type="xs:date"/>
                                        <xs:element name="mesto_rodjenja" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="prebivaliste">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="adresa">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="ulica" type="xs:string"/>
                                                  <xs:element name="broj" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="mesto_stanovanja" type="xs:string"/>
                                        <xs:element name="opstina" type="t:TLokacija"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="fiksni_telefon" type="t:TFiksniTelefon"/>
                            <xs:element name="mobilni_telefon" type="t:TTelefon"/>

                            <xs:element name="email" type="t:TEmail"/>
                            <xs:element name="radni_status">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="zaposlen"/>
                                        <xs:enumeration value="nezaposlen"/>
                                        <xs:enumeration value="penzioner"/>
                                        <xs:enumeration value="ucenik"/>
                                        <xs:enumeration value="student"/>
                                        <xs:enumeration value="dete"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="zanimanje">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="zdravstvena_zastita"/>
                                        <xs:enumeration value="socijalna_zastita"/>
                                        <xs:enumeration value="prosveta"/>
                                        <xs:enumeration value="mup"/>
                                        <xs:enumeration value="vojska_rs"/>
                                        <xs:enumeration value="drugo"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="socijalna_zastita">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="korisnik" type="xs:boolean"/>
                                        <xs:element name="sediste" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="naziv" type="xs:string"/>
                                                  <xs:element name="opstina" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="izjava_saglasnosti">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="saglasnost" type="xs:boolean"/>
                                        <xs:element name="naziv_leka" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="datum_popunjavanja" use="required" type="xs:date"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="evidencija_o_vakcinaciji" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="zdravstvena_ustanova" type="xs:string"/>
                            <xs:element name="vakcinacijski_punkt" type="xs:integer"/>
                            <xs:element name="lekar">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ime" type="xs:string"/>
                                        <xs:element name="prezime" type="xs:string"/>
                                        <xs:element name="telefon" type="t:TFiksniTelefon"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="vakcine">
                                <xs:complexType>
                                    <xs:sequence>
<<<<<<< HEAD
                                        <xs:sequence minOccurs="0" maxOccurs="2">
=======
                                        <xs:sequence minOccurs="1" maxOccurs="unbounded">
>>>>>>> develop
                                            <xs:element name="vakcina">
                                                <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="naziv" type="t:TNazivVakcine"/>

                                                  <xs:element name="datum_izdavanja" type="xs:date"/>
                                                  <xs:element name="nacin_davanja" type="xs:string"/>
                                                  <xs:element name="ekstremitet">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:enumeration value="LR"/>
                                                  <xs:enumeration value="DR"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                  <xs:element name="serija" type="xs:string"/>
                                                  <xs:element name="proizvodjac" type="xs:string"/>
                                                  <xs:element name="nezeljena_reakcija"
                                                  type="xs:string"/>
                                                  </xs:sequence>
                                                </xs:complexType>
                                                <xs:unique name="vakcinaNazivUnique">
                                                  <xs:selector xpath="o:vakcina"/>
                                                  <xs:field xpath="@naziv"/>
                                                </xs:unique>
                                            </xs:element>
                                        </xs:sequence>

                                        <xs:element name="kontraindikacije">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="datum_utvrdjivanja"
                                                  type="xs:date"/>
                                                  <xs:element name="dijagnoza" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="odluka_komisije" type="xs:boolean"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="about" type="xs:string" use="required"/>
            <xs:attribute name="href" type="xs:string"/>
            <xs:attribute fixed="pred:parentTo" name="rel" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>



</xs:schema>

=== jovansx/vaccination-system/dokumenti/saglasnost_za_imunizaciju.xml
<?xml version="1.0" encoding="UTF-8"?>
<saglasnost_za_imunizaciju xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://www.akatsuki.org/saglasnost_za_imunizaciju"
    xmlns:t="http://www.akatsuki.org/tipovi"
    xsi:schemaLocation="http://www.akatsuki.org saglasnost_za_imunizaciju.xsd
    http://www.akatsuki.org/tipovi tipovi.xsd"
    xmlns:pred="http://www.akatsuki.org/rdf/examples/predicate/"
    about="http://www.akatsuki.org/saglasnosti/1510999800078_0">
    <pacijent datum_popunjavanja="1999-10-15">
        <drzavljanstvo>
            <srpsko>
                <id_broj property="pred:id_broj" datatype="xs:string">1510999800078</id_broj>
            </srpsko>
        </drzavljanstvo>
        <prezime property="pred:prezime" datatype="xs:string">Buljevic</prezime>
        <ime property="pred:ime" datatype="xs:string">Aleksandar</ime>
        <ime_roditelja>Mladen</ime_roditelja>
        <pol property="pred:pol" datatype="xs:string">Muski</pol>
        <rodjenje>
            <datum_rodjenja>1999-10-15</datum_rodjenja>
            <mesto_rodjenja>Veternik</mesto_rodjenja>
        </rodjenje>
        <prebivaliste>
            <adresa>
                <ulica>Vladike Maksima</ulica>
                <broj>69</broj>
            </adresa>
            <mesto_stanovanja>Veternik</mesto_stanovanja>
            <opstina property="pred:lokacija" datatype="xs:string">Novi Sad</opstina>
        </prebivaliste>
        <fiksni_telefon>(021) 641-3876</fiksni_telefon>
        <mobilni_telefon>0691782912</mobilni_telefon>
        <email>abuljevic8@gmail.com</email>
        <radni_status>student</radni_status>
        <zanimanje>drugo</zanimanje>
        <socijalna_zastita>
            <korisnik>true</korisnik>
        </socijalna_zastita>
        <izjava_saglasnosti>
            <saglasnost>true</saglasnost>
            <naziv_leka>Aspirin</naziv_leka>
        </izjava_saglasnosti>
    </pacijent>
</saglasnost_za_imunizaciju>
